version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: admin
      #MONGO_INITDB_ROOT_PASSWORD: secret
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongodb.env
    #networks:
      #- goals
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "80:80"
    #command: chown -R 1001:1001 /app/logs
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  mongodb:
  logs: